#!/bin/sh

[ -r /etc/runit/runit.conf ] && . /etc/runit/runit.conf

msg() {
    echo -e "\e[0;32m*\e[0m $@"
}

[ -x /etc/runit/rc.shutdown ] && /etc/runit/rc.shutdown

msg "Saving random seed..."
dd if=/dev/urandom of=/var/lib/random-seed count=1 bs=512 2>/dev/null

if [ -n "$HARDWARECLOCK" ]; then
    case "$HARDWARECLOCK" in
		UTC)       CLOCKPARAMS="--utc" ;;
		localtime) CLOCKPARAMS="--localtime" ;;
	esac
    msg "Setting up RTC to '${HARDWARECLOCK}'..."
	hwclock --systohc "$CLOCKPARAMS"
fi

msg "Sending TERM signal to processes..."
pkill --inverse -s0,1 -TERM
sleep 1
msg "Sending KILL signal to processes..."
pkill --inverse -s0,1 -KILL

msg "Deactivating all swap files/partitions..."
swapoff -a

msg "Bringing down the loopback interface..."
ip link set lo down
      
msg "Unmounting all other currently mounted file systems..."
umount --all --detach-loop --read-only \
       --types notmpfs,nosysfs,nodevtmpfs,noproc,nodevpts >/dev/null

mount --options remount,ro /

sync

sleep 1
